<?php
require 'vendor/autoload.php';
require_once 'includes/db.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Border;

$project_id = $_GET['id'] ?? 0;

if (!$project_id) {
    die("Project ID not provided.");
}

try {
    // Fetch Project
    $stmt = $pdo->prepare("SELECT p.*, u.username as creator_name FROM projects p LEFT JOIN users u ON p.created_by = u.id WHERE p.id = :id");
    $stmt->execute(['id' => $project_id]);
    $project = $stmt->fetch();

    if (!$project) {
        die("Project not found.");
    }

    // Fetch Stages
    $stmt = $pdo->prepare("SELECT * FROM project_stages WHERE project_id = :id ORDER BY id ASC");
    $stmt->execute(['id' => $project_id]);
    $stages = $stmt->fetchAll();

} catch (Exception $e) {
    die("Error: " . $e->getMessage());
}

$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();

// Set document properties
$spreadsheet->getProperties()->setCreator('Validation System')
    ->setLastModifiedBy('Validation System')
    ->setTitle('Project Validation Report')
    ->setSubject('Validation Report')
    ->setDescription('Project Validation Report generated by Validation System');

// --- Header ---
$sheet->setCellValue('A1', 'Project Validation Report');
$sheet->mergeCells('A1:B1');
$sheet->getStyle('A1')->getFont()->setBold(true)->setSize(16)->setColor(new \PhpOffice\PhpSpreadsheet\Style\Color(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_DARKBLUE));
$sheet->getStyle('A1')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

// --- Project Details ---
$row = 3;
$sheet->setCellValue('A' . $row, 'Project Details');
$sheet->mergeCells('A' . $row . ':B' . $row);
$sheet->getStyle('A' . $row)->getFont()->setBold(true)->setColor(new \PhpOffice\PhpSpreadsheet\Style\Color(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE));
$sheet->getStyle('A' . $row)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setARGB('FF1565C0'); // Blue
$sheet->getStyle('A' . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

$row++;
$details = [
    'Project Name' => $project['name'],
    'Status' => $project['status'],
    'Created By' => $project['creator_name'] ?? 'Unknown',
    'Software Name' => $project['software'],
    'Version' => $project['version'],
    'Description' => $project['description'],
    'Created' => date('M d, Y, h:i A', strtotime($project['created_at'])),
    'Last Updated' => date('M d, Y, h:i A', strtotime($project['updated_at'] ?? $project['created_at']))
];

foreach ($details as $label => $value) {
    $sheet->setCellValue('A' . $row, $label);
    $sheet->setCellValue('B' . $row, $value);
    $sheet->getStyle('A' . $row)->getFont()->setBold(true);
    // Wrap text for description
    if ($label === 'Description') {
        $sheet->getStyle('B' . $row)->getAlignment()->setWrapText(true);
    }
    $row++;
}

// Border for Project Details
$sheet->getStyle('A3:B' . ($row - 1))->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN);

// --- Stages Summary ---
$row += 2;
$sheet->setCellValue('A' . $row, 'Validation Stages Summary');
$sheet->mergeCells('A' . $row . ':C' . $row);
$sheet->getStyle('A' . $row)->getFont()->setBold(true)->setColor(new \PhpOffice\PhpSpreadsheet\Style\Color(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_WHITE));
$sheet->getStyle('A' . $row)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setARGB('FF1565C0'); // Blue
$sheet->getStyle('A' . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

$row++;
$headers = ['Stage Name', 'Status', 'Notes'];
$col = 'A';
foreach ($headers as $header) {
    $sheet->setCellValue($col . $row, $header);
    $sheet->getStyle($col . $row)->getFont()->setBold(true);
    $sheet->getStyle($col . $row)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setARGB('FFC6FF00'); // Green Accent
    $col++;
}

$row++;
foreach ($stages as $stage) {
    $sheet->setCellValue('A' . $row, $stage['name']);
    $sheet->setCellValue('B' . $row, $stage['status']);
    
    $note = ($stage['status'] === 'Completed') ? "Completed on " . date('M d, Y') : "Pending";
    $sheet->setCellValue('C' . $row, $note);
    
    $row++;
}

// Border for Stages
$sheet->getStyle('A' . ($row - count($stages) - 2) . ':C' . ($row - 1))->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN);

// Column Sizing
$sheet->getColumnDimension('A')->setWidth(30);
$sheet->getColumnDimension('B')->setWidth(20);
$sheet->getColumnDimension('C')->setWidth(30);

// Output
$filename = "Project_Report_" . preg_replace('/[^a-zA-Z0-9]/', '_', $project['name']) . ".xlsx";

header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment;filename="' . $filename . '"');
header('Cache-Control: max-age=0');

$writer = new Xlsx($spreadsheet);
$writer->save('php://output');
exit;
